# Enrich data with context attributes

In [44]:
import pandas as pd
import pm4py

import requests
from PyPDF2 import PdfReader
from io import BytesIO
import ast

In [45]:

INPUT_FILE_NAME = 'berlin-preprocessed-gesetzgebung-2006-2020.xes'
OUTPUT_FILE_NAME = 'berlin-preprocessed-gesetzgebung-2006-2020_with_context.xes'
INPUT_FILE_NAME_EARLIER = 'berlin-gesetzgebung-contained-2006-2020_with_context_2.xes'


#INPUT_FILE_NAME = 'baden-württemberg-preprocessed-gesetzgebung-gesetz-2006-2020_processed.xes'
#OUTPUT_FILE_NAME = 'baden-württemberg-preprocessed-gesetzgebung-gesetz-2006-2020_processed_with_context.xes'
#INPUT_FILE_NAME_EARLIER = 'baden-württemberg-gesetzgebung-contained-2006-2020_with_context_2.xes'


#INPUT_FILE_NAME = 'brandenburg-preprocessed-gesetzgebung-2006-2020_processed.xes'
#OUTPUT_FILE_NAME = 'brandenburg-preprocessed-gesetzgebung-2006-2020_processed_with_context.xes'
#INPUT_FILE_NAME_EARLIER = 'brandenburg-gesetzgebung-contained-2006-2020_with_context_2.xes'


#bundeslandCapitalized = "Berlin"
bundeslandCapitalized = "Baden-Württemberg"
#bundeslandCapitalized = "Brandenburg"


CASE_ID_COL = 'case:concept:name'
TIMESTAMP_COL = 'time:timestamp'
ACTIVITY_COL = 'concept:name'

# Define election years
election_years = {
    'berlin': [1990, 1995, 1999, 2001, 2006, 2011, 2016, 2021, 2023],
    'brandenburg': [1990, 1994, 1999, 2004, 2009, 2014, 2019],
    'baden-württemberg': [1992, 1996, 2001, 2006, 2011, 2016, 2021]
}

passed_bills_activities_berlin = ['Gesetz- und Verordnungsblatt', 'Bekanntmachung (Gesetz- und Verordnungsblatt)']
passed_bills_activities_bawue = ["Gesetz", "Gesetzblatt für Baden-Württemberg"]
passed_bills_activities_brandenburg = ["Gesetz", "Gesetz- und Verordnungsblatt"]

possible_passed_bills_activities = passed_bills_activities_berlin + passed_bills_activities_bawue + passed_bills_activities_brandenburg

In [46]:
df = pm4py.read_xes(INPUT_FILE_NAME)
print(len(df), 'rows read from', INPUT_FILE_NAME)
df = df.sort_values(TIMESTAMP_COL, ignore_index=True)
#df.info()
#df.head()

df_earlier = pm4py.read_xes(INPUT_FILE_NAME_EARLIER)

parsing log, completed traces :: 100%|██████████| 731/731 [00:00<00:00, 3343.96it/s]

5223 rows read from berlin-preprocessed-gesetzgebung-2006-2020.xes

parsing log, completed traces :: 100%|██████████| 839/839 [00:00<00:00, 2530.14it/s]

### Attributes/Context to add:

* start_month **[DONE]** -> instead of Parlamentsferien (could also be looked up)
* start_weekday **[DONE]**
* count_urheber **[DONE]**
* WIP **[DONE]**
* Bytes of PDF file that is linked to first activity **[DONE]**
* Professionalism data (Appeldorn + Fortunato) **[DONE]**
* is_election_year **[DONE]**

In [47]:

def add_case_attribute(df, id_value_obj, attribute_name):
    df[attribute_name] = df[CASE_ID_COL].map(id_value_obj)

def get_month_attribute():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        month = df[TIMESTAMP_COL][i].month
        if case_id not in result_obj:
            result_obj[case_id] = month
    return result_obj

def get_weekday_attribute():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        weekday = df[TIMESTAMP_COL][i].weekday()
        if case_id not in result_obj:
            result_obj[case_id] = weekday
    return result_obj

# just get the urheber of the first activity as a case attribute
def get_urheber_first_activity():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        if case_id not in result_obj:
            urheber = df["Urheber"][i]
            result_obj[case_id] = urheber
    return result_obj

def get_urheber_count_first_activity():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        urheber = df["Urheber"][i]
        if case_id not in result_obj:
            if (urheber == "nan"): # TODO: what does nan mean here??
                result_obj[case_id] = None
            else:
                result_obj[case_id] = urheber.count(',') + 1 if isinstance(urheber, str) else 0
    return result_obj


def get_case_times_helper():
    result_obj = {}
    for case_id in df[CASE_ID_COL].unique():
        case_df = df[df[CASE_ID_COL] == case_id]
        start_time = case_df[TIMESTAMP_COL].min()
        end_time = case_df[TIMESTAMP_COL].max()
        result_obj[case_id] = {'start_time': start_time, 'end_time': end_time}
    return result_obj

def get_is_election_year():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        year = df[TIMESTAMP_COL][i].year
        if case_id not in result_obj:
            if (year in election_years[bundeslandCapitalized.lower()]):
                result_obj[case_id] = 1
            else:
                result_obj[case_id] = 0
    return result_obj

def get_WIP_during_start():
    # Get start_time and end_time for each case
    case_times = get_case_times_helper()
    # Create a DataFrame from case_times
    case_df = pd.DataFrame.from_dict(case_times, orient="index").reset_index()
    case_df.columns = [CASE_ID_COL, "start_time", "end_time"]
    
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        start_time = df[TIMESTAMP_COL][i]
        if case_id not in result_obj:
            result_obj[case_id] = ((case_df["start_time"] <= start_time) & (case_df["end_time"] > start_time)).sum()
    return result_obj

def get_pdf_information_helper(url):
    
    # handle case where there is a list of documents
    # for example pdf and docx
    if (url.startswith("[") and url.endswith("]")):
        print(url)
        filenames = ast.literal_eval(url)
        for filename in filenames:
            if filename.endswith(".pdf"):
                url = filename
                break
            
    try:
        # Get the PDF file as bytes
        print("getting file...")
        response = requests.get(url, timeout=60)
    except requests.exceptions.Timeout:
        print("The request timed out")
        return 0, 0
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")
        return 0, 0 

    if response.status_code == 200:
        print("got file...")
        pdf_bytes = response.content

        try:
            # Load PDF into PyPDF2 PdfReader
            pdf_reader = PdfReader(BytesIO(pdf_bytes))
            
            # Extract text and calculate word count
            total_word_count = 0
            for page in pdf_reader.pages:
                text = page.extract_text()
                if text:  # Ensure the page has extractable text
                    total_word_count += len(text.split())
            return len(response.content), total_word_count
        except Exception as e:
            print(f"Error processing PDF: {e}")
            return 0, 0
    else:
        print(f"Error getting PDF: {response.status_code}")
        return 0, 0

def get_pdf_information():
    result_obj_bytes = {}
    result_obj_word_count = {}
    for i in range(len(df)):
        print("i/len(df):", i, "/", len(df))
        case_id = df[CASE_ID_COL][i]
        url = df["LokURL"][i]
        if case_id not in result_obj_bytes:
            if url == "nan":
                bytes, word_count = (0, 0)
            else:
                bytes, word_count = get_pdf_information_helper(url)
                
            print({"bytes": bytes, "total_word_count": word_count})
            result_obj_bytes[case_id] = bytes
            result_obj_word_count[case_id] = word_count
    return result_obj_bytes, result_obj_word_count

def add_pdf_case_attributes(df, id_value_obj_bytes, id_value_obj_word_count, attribute_bytes, attribute_word_count):
    df[attribute_bytes] = df[CASE_ID_COL].map(id_value_obj_bytes)
    df[attribute_word_count] = df[CASE_ID_COL].map(id_value_obj_word_count)
    
def get_professionalism_data():
    # load professionalization data to compare to
    # Read the data from replication.txt using | as the separator and including the header data
    readData = pd.read_csv('../LegislativeCapacityInGermanysParliaments/replication.txt', sep='|')
    readData_af = pd.read_csv('../LegislativeCapacityInGermanysParliaments/afScores.txt', sep=' ')
    data = {}
    data_af = {}
    
    bundesland = bundeslandCapitalized
    if(bundesland == "Baden-Württemberg"):
        data[bundesland.lower()] = readData[readData['land'] == "Baden-Wurttemberg"]
        data_af[bundesland.lower()] = readData_af[readData_af['land'] == "Baden-Wurttemberg"]
    else: 
        data[bundesland.lower()] = readData[readData['land'] == bundesland]
        data_af[bundesland.lower()] = readData_af[readData_af['land'] == bundesland]

    # first, we'll specify a squire-type scale
    data[bundesland.lower()]['squire'] = 1/3 * (data[bundesland.lower()]['salary'] / data[bundesland.lower()]['fp_mp_salary_2015']) + \
                    1/3 * (data[bundesland.lower()]['staff'] / data[bundesland.lower()]['fp_staffmp_2015']) + \
                    1/6 * (data[bundesland.lower()]['commDays'] / data[bundesland.lower()]['fp_com_sessions']) + \
                    1/6 * (data[bundesland.lower()]['plenDays'] / data[bundesland.lower()]['fp_plenary_sessions'])

    return data, data_af
             

def get_professionalism_values(data, columnName):
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        year = df[TIMESTAMP_COL][i].year
        if case_id not in result_obj:
            if (data.loc[data['year'] == year, columnName].empty):
                result_obj[case_id] = None
            else:
                result_obj[case_id] = data.loc[data['year'] == year, columnName].values[0]
    return result_obj
       

def get_is_passed_bill():
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        activityType = df[ACTIVITY_COL][i]
        if activityType in possible_passed_bills_activities:
            result_obj[case_id] = 1
        elif case_id not in result_obj:
            result_obj[case_id] = 0
    return result_obj

In [48]:

#pdf_info_bytes, pdf_info_word_count = get_pdf_information()

def get_pdf_information_fromOtherFile_helper(case_id, df):
    entry = df[df[CASE_ID_COL] == case_id].iloc[0]
    bytes = entry.get("case:pdf_bytes")
    word_count = entry.get("case:pdf_word_count")
    return (bytes, word_count)

def add_pdf_case_attributes_otherDoc(df, id_value_obj_bytes, id_value_obj_word_count, attribute_bytes, attribute_word_count):
    print("Mapping bytes:")
    df[attribute_bytes] = df[CASE_ID_COL].astype(int).map(id_value_obj_bytes)
    print(df[[CASE_ID_COL, attribute_bytes]].head())
    
    print("Mapping word count:")
    df[attribute_word_count] = df[CASE_ID_COL].astype(int).map(id_value_obj_word_count)
    print(df[[CASE_ID_COL, attribute_word_count]].head())

def get_pdf_information_fromOtherFile(df):
    result_obj_bytes = {}
    result_obj_word_count = {}
    for i in range(len(df)):
        print("i/len(df):", i, "/", len(df))
        case_id = df[CASE_ID_COL][i]
        url = df["LokURL"][i]
        case_id_int = int(float(df[CASE_ID_COL][i]))
        if case_id_int not in result_obj_bytes:
            if url == "nan":
                bytes, word_count = (0, 0)
            else:
                bytes, word_count = get_pdf_information_fromOtherFile_helper(case_id, df)
                
            print({"bytes": bytes, "total_word_count": word_count})
            result_obj_bytes[case_id_int] = bytes
            result_obj_word_count[case_id_int] = word_count
    return result_obj_bytes, result_obj_word_count

pdf_info_bytes, pdf_info_word_count = get_pdf_information_fromOtherFile(df_earlier)

i/len(df): 0 / 5735
{'bytes': np.int64(197170), 'total_word_count': np.int64(3692)}
i/len(df): 1 / 5735
i/len(df): 2 / 5735
i/len(df): 3 / 5735
i/len(df): 4 / 5735
i/len(df): 5 / 5735
{'bytes': np.int64(102946), 'total_word_count': np.int64(2103)}
i/len(df): 6 / 5735
i/len(df): 7 / 5735
i/len(df): 8 / 5735
i/len(df): 9 / 5735
i/len(df): 10 / 5735
i/len(df): 11 / 5735
i/len(df): 12 / 5735
{'bytes': np.int64(577141), 'total_word_count': np.int64(10758)}
i/len(df): 13 / 5735
i/len(df): 14 / 5735
i/len(df): 15 / 5735
i/len(df): 16 / 5735
i/len(df): 17 / 5735
i/len(df): 18 / 5735
i/len(df): 19 / 5735
i/len(df): 20 / 5735
{'bytes': np.int64(54723), 'total_word_count': np.int64(2607)}
i/len(df): 21 / 5735
i/len(df): 22 / 5735
i/len(df): 23 / 5735
i/len(df): 24 / 5735
i/len(df): 25 / 5735
i/len(df): 26 / 5735
i/len(df): 27 / 5735
{'bytes': np.int64(125855), 'total_word_count': np.int64(6503)}
i/len(df): 28 / 5735
i/len(df): 29 / 5735
i/len(df): 30 / 5735
i/len(df): 31 / 5735
i/len(df): 32 / 5735
i/len(df): 33 / 5735
i/len(df): 34 / 5735
{'bytes': np.int64(110806), 'total_word_count': np.int64(646)}
i/len(df): 35 / 5735
i/len(df): 36 / 5735
{'bytes': np.int64(47402), 'total_word_count': np.int64(1065)}
i/len(df): 37 / 5735
i/len(df): 38 / 5735
i/len(df): 39 / 5735
i/len(df): 40 / 5735
i/len(df): 41 / 5735
i/len(df): 42 / 5735
{'bytes': np.int64(46928), 'total_word_count': np.int64(967)}
i/len(df): 43 / 5735
i/len(df): 44 / 5735
i/len(df): 45 / 5735
i/len(df): 46 / 5735
i/len(df): 47 / 5735
i/len(df): 48 / 5735
{'bytes': np.int64(191453), 'total_word_count': np.int64(16555)}
i/len(df): 49 / 5735
i/len(df): 50 / 5735
i/len(df): 51 / 5735
i/len(df): 52 / 5735
i/len(df): 53 / 5735
i/len(df): 54 / 5735
i/len(df): 55 / 5735
{'bytes': np.int64(61031), 'total_word_count': np.int64(1322)}
i/len(df): 56 / 5735
i/len(df): 57 / 5735
i/len(df): 58 / 5735
i/len(df): 59 / 5735
i/len(df): 60 / 5735
i/len(df): 61 / 5735
i/len(df): 62 / 5735
{'bytes': np.int64(3067454), 'total_word_count': np.int64(3655)}
i/len(df): 63 / 5735
i/len(df): 64 / 5735
i/len(df): 65 / 5735
i/len(df): 66 / 5735
i/len(df): 67 / 5735
i/len(df): 68 / 5735
i/len(df): 69 / 5735
i/len(df): 70 / 5735
{'bytes': np.int64(28557), 'total_word_count': np.int64(500)}
i/len(df): 71 / 5735
i/len(df): 72 / 5735
i/len(df): 73 / 5735
i/len(df): 74 / 5735
i/len(df): 75 / 5735
i/len(df): 76 / 5735
i/len(df): 77 / 5735
i/len(df): 78 / 5735
{'bytes': np.int64(394905), 'total_word_count': np.int64(21154)}
i/len(df): 79 / 5735
i/len(df): 80 / 5735
i/len(df): 81 / 5735
i/len(df): 82 / 5735
i/len(df): 83 / 5735
i/len(df): 84 / 5735
i/len(df): 85 / 5735
i/len(df): 86 / 5735
i/len(df): 87 / 5735
{'bytes': np.int64(1477162), 'total_word_count': np.int64(51645)}
i/len(df): 88 / 5735
i/len(df): 89 / 5735
i/len(df): 90 / 5735
i/len(df): 91 / 5735
i/len(df): 92 / 5735
i/len(df): 93 / 5735
i/len(df): 94 / 5735
i/len(df): 95 / 5735
{'bytes': np.int64(1081378), 'total_word_count': np.int64(34338)}
i/len(df): 96 / 5735
i/len(df): 97 / 5735
i/len(df): 98 / 5735
i/len(df): 99 / 5735
i/len(df): 100 / 5735
i/len(df): 101 / 5735
i/len(df): 102 / 5735
{'bytes': np.int64(51364), 'total_word_count': np.int64(1601)}
i/len(df): 103 / 5735
i/len(df): 104 / 5735
i/len(df): 105 / 5735
i/len(df): 106 / 5735
i/len(df): 107 / 5735
i/len(df): 108 / 5735
{'bytes': np.int64(107296), 'total_word_count': np.int64(485)}
i/len(df): 109 / 5735
i/len(df): 110 / 5735
i/len(df): 111 / 5735
i/len(df): 112 / 5735
i/len(df): 113 / 5735
{'bytes': np.int64(300905), 'total_word_count': np.int64(6782)}
i/len(df): 114 / 5735
i/len(df): 115 / 5735
i/len(df): 116 / 5735
i/len(df): 117 / 5735
i/len(df): 118 / 5735
i/len(df): 119 / 5735
i/len(df): 120 / 5735
i/len(df): 121 / 5735
i/len(df): 122 / 5735
{'bytes': np.int64(83201), 'total_word_count': np.int64(2107)}
i/len(df): 123 / 5735
i/len(df): 124 / 5735
i/len(df): 125 / 5735
i/len(df): 126 / 5735
i/len(df): 127 / 5735
i/len(df): 128 / 5735
i/len(df): 129 / 5735
{'bytes': np.int64(168439), 'total_word_count': np.int64(8502)}
i/len(df): 130 / 5735
i/len(df): 131 / 5735
i/len(df): 132 / 5735
i/len(df): 133 / 5735
i/len(df): 134 / 5735
i/len(df): 135 / 5735
{'bytes': np.int64(158992), 'total_word_count': np.int64(4956)}
i/len(df): 136 / 5735
i/len(df): 137 / 5735
i/len(df): 138 / 5735
i/len(df): 139 / 5735
i/len(df): 140 / 5735
i/len(df): 141 / 5735
{'bytes': np.int64(364688), 'total_word_count': np.int64(30678)}
i/len(df): 142 / 5735
i/len(df): 143 / 5735
i/len(df): 144 / 5735
i/len(df): 145 / 5735
i/len(df): 146 / 5735
i/len(df): 147 / 5735
i/len(df): 148 / 5735
i/len(df): 149 / 5735
i/len(df): 150 / 5735
{'bytes': np.int64(29310), 'total_word_count': np.int64(632)}
i/len(df): 151 / 5735
i/len(df): 152 / 5735
{'bytes': np.int64(23891), 'total_word_count': np.int64(338)}
i/len(df): 153 / 5735
i/len(df): 154 / 5735
i/len(df): 155 / 5735
i/len(df): 156 / 5735
i/len(df): 157 / 5735
i/len(df): 158 / 5735
{'bytes': np.int64(137253), 'total_word_count': np.int64(3919)}
i/len(df): 159 / 5735
i/len(df): 160 / 5735
i/len(df): 161 / 5735
i/len(df): 162 / 5735
i/len(df): 163 / 5735
i/len(df): 164 / 5735
i/len(df): 165 / 5735
i/len(df): 166 / 5735
{'bytes': np.int64(233687), 'total_word_count': np.int64(11431)}
i/len(df): 167 / 5735
i/len(df): 168 / 5735
i/len(df): 169 / 5735
i/len(df): 170 / 5735
i/len(df): 171 / 5735
i/len(df): 172 / 5735
i/len(df): 173 / 5735
{'bytes': np.int64(61353), 'total_word_count': np.int64(3883)}
i/len(df): 174 / 5735
i/len(df): 175 / 5735
i/len(df): 176 / 5735
i/len(df): 177 / 5735
i/len(df): 178 / 5735
i/len(df): 179 / 5735
i/len(df): 180 / 5735
i/len(df): 181 / 5735
{'bytes': np.int64(287297), 'total_word_count': np.int64(5087)}
i/len(df): 182 / 5735
i/len(df): 183 / 5735
i/len(df): 184 / 5735
i/len(df): 185 / 5735
i/len(df): 186 / 5735
i/len(df): 187 / 5735
{'bytes': np.int64(24069), 'total_word_count': np.int64(382)}
i/len(df): 188 / 5735
i/len(df): 189 / 5735
{'bytes': np.int64(25083), 'total_word_count': np.int64(569)}
i/len(df): 190 / 5735
i/len(df): 191 / 5735
i/len(df): 192 / 5735
i/len(df): 193 / 5735
i/len(df): 194 / 5735
i/len(df): 195 / 5735
i/len(df): 196 / 5735
i/len(df): 197 / 5735
{'bytes': np.int64(78771), 'total_word_count': np.int64(4001)}
i/len(df): 198 / 5735
i/len(df): 199 / 5735
i/len(df): 200 / 5735
i/len(df): 201 / 5735
i/len(df): 202 / 5735
i/len(df): 203 / 5735
i/len(df): 204 / 5735
{'bytes': np.int64(24541), 'total_word_count': np.int64(811)}
i/len(df): 205 / 5735
i/len(df): 206 / 5735
i/len(df): 207 / 5735
i/len(df): 208 / 5735
i/len(df): 209 / 5735
i/len(df): 210 / 5735
i/len(df): 211 / 5735
i/len(df): 212 / 5735
{'bytes': np.int64(19539), 'total_word_count': np.int64(287)}
i/len(df): 213 / 5735
i/len(df): 214 / 5735
i/len(df): 215 / 5735
i/len(df): 216 / 5735
i/len(df): 217 / 5735
i/len(df): 218 / 5735
i/len(df): 219 / 5735
{'bytes': np.int64(1308024), 'total_word_count': np.int64(30540)}
i/len(df): 220 / 5735
i/len(df): 221 / 5735
i/len(df): 222 / 5735
i/len(df): 223 / 5735
i/len(df): 224 / 5735
i/len(df): 225 / 5735
i/len(df): 226 / 5735
i/len(df): 227 / 5735
i/len(df): 228 / 5735
i/len(df): 229 / 5735
i/len(df): 230 / 5735
i/len(df): 231 / 5735
i/len(df): 232 / 5735
{'bytes': np.int64(91320), 'total_word_count': np.int64(8660)}
i/len(df): 233 / 5735
i/len(df): 234 / 5735
i/len(df): 235 / 5735
i/len(df): 236 / 5735
i/len(df): 237 / 5735
i/len(df): 238 / 5735
i/len(df): 239 / 5735
{'bytes': np.int64(66335), 'total_word_count': np.int64(5301)}
i/len(df): 240 / 5735
i/len(df): 241 / 5735
i/len(df): 242 / 5735
i/len(df): 243 / 5735
i/len(df): 244 / 5735
i/len(df): 245 / 5735
i/len(df): 246 / 5735
{'bytes': np.int64(80139), 'total_word_count': np.int64(5847)}
i/len(df): 247 / 5735
i/len(df): 248 / 5735
i/len(df): 249 / 5735
i/len(df): 250 / 5735
i/len(df): 251 / 5735
i/len(df): 252 / 5735
{'bytes': np.int64(338471), 'total_word_count': np.int64(38441)}
i/len(df): 253 / 5735
i/len(df): 254 / 5735
i/len(df): 255 / 5735
i/len(df): 256 / 5735
i/len(df): 257 / 5735
i/len(df): 258 / 5735
i/len(df): 259 / 5735
i/len(df): 260 / 5735
i/len(df): 261 / 5735
{'bytes': np.int64(22561), 'total_word_count': np.int64(625)}
i/len(df): 262 / 5735
i/len(df): 263 / 5735
i/len(df): 264 / 5735
{'bytes': np.int64(41714), 'total_word_count': np.int64(2089)}
i/len(df): 265 / 5735
i/len(df): 266 / 5735
i/len(df): 267 / 5735
i/len(df): 268 / 5735
i/len(df): 269 / 5735
i/len(df): 270 / 5735
{'bytes': np.int64(150329), 'total_word_count': np.int64(12086)}
i/len(df): 271 / 5735
i/len(df): 272 / 5735
i/len(df): 273 / 5735
i/len(df): 274 / 5735
i/len(df): 275 / 5735
i/len(df): 276 / 5735
i/len(df): 277 / 5735
{'bytes': np.int64(89091), 'total_word_count': np.int64(5569)}
i/len(df): 278 / 5735
i/len(df): 279 / 5735
i/len(df): 280 / 5735
i/len(df): 281 / 5735
i/len(df): 282 / 5735
i/len(df): 283 / 5735
i/len(df): 284 / 5735
{'bytes': np.int64(20324), 'total_word_count': np.int64(385)}
i/len(df): 285 / 5735
i/len(df): 286 / 5735
i/len(df): 287 / 5735
i/len(df): 288 / 5735
i/len(df): 289 / 5735
i/len(df): 290 / 5735
{'bytes': np.int64(5004393), 'total_word_count': np.int64(2951)}
i/len(df): 291 / 5735
i/len(df): 292 / 5735
i/len(df): 293 / 5735
i/len(df): 294 / 5735
i/len(df): 295 / 5735
i/len(df): 296 / 5735
{'bytes': np.int64(63329), 'total_word_count': np.int64(2227)}
i/len(df): 297 / 5735
i/len(df): 298 / 5735
i/len(df): 299 / 5735
i/len(df): 300 / 5735
i/len(df): 301 / 5735
i/len(df): 302 / 5735
i/len(df): 303 / 5735
{'bytes': np.int64(289488), 'total_word_count': np.int64(4709)}
i/len(df): 304 / 5735
i/len(df): 305 / 5735
i/len(df): 306 / 5735
i/len(df): 307 / 5735
i/len(df): 308 / 5735
i/len(df): 309 / 5735
i/len(df): 310 / 5735
{'bytes': np.int64(27954), 'total_word_count': np.int64(570)}
i/len(df): 311 / 5735
i/len(df): 312 / 5735
i/len(df): 313 / 5735
i/len(df): 314 / 5735
i/len(df): 315 / 5735
i/len(df): 316 / 5735
i/len(df): 317 / 5735
{'bytes': np.int64(22533), 'total_word_count': np.int64(247)}
i/len(df): 318 / 5735
i/len(df): 319 / 5735
i/len(df): 320 / 5735
i/len(df): 321 / 5735
i/len(df): 322 / 5735
i/len(df): 323 / 5735
{'bytes': np.int64(20783), 'total_word_count': np.int64(471)}
i/len(df): 324 / 5735
i/len(df): 325 / 5735
i/len(df): 326 / 5735
i/len(df): 327 / 5735
i/len(df): 328 / 5735
i/len(df): 329 / 5735
{'bytes': np.int64(21369), 'total_word_count': np.int64(510)}
i/len(df): 330 / 5735
i/len(df): 331 / 5735
i/len(df): 332 / 5735
i/len(df): 333 / 5735
i/len(df): 334 / 5735
i/len(df): 335 / 5735
{'bytes': np.int64(41611), 'total_word_count': np.int64(1851)}
i/len(df): 336 / 5735
i/len(df): 337 / 5735
i/len(df): 338 / 5735
i/len(df): 339 / 5735
i/len(df): 340 / 5735
i/len(df): 341 / 5735
{'bytes': np.int64(19728), 'total_word_count': np.int64(189)}
i/len(df): 342 / 5735
i/len(df): 343 / 5735
i/len(df): 344 / 5735
i/len(df): 345 / 5735
i/len(df): 346 / 5735
i/len(df): 347 / 5735
{'bytes': np.int64(16973), 'total_word_count': np.int64(236)}
i/len(df): 348 / 5735
i/len(df): 349 / 5735
i/len(df): 350 / 5735
i/len(df): 351 / 5735
i/len(df): 352 / 5735
i/len(df): 353 / 5735
{'bytes': np.int64(63324), 'total_word_count': np.int64(4192)}
i/len(df): 354 / 5735
i/len(df): 355 / 5735
i/len(df): 356 / 5735
i/len(df): 357 / 5735
i/len(df): 358 / 5735
{'bytes': np.int64(19401), 'total_word_count': np.int64(346)}
i/len(df): 359 / 5735
i/len(df): 360 / 5735
i/len(df): 361 / 5735
i/len(df): 362 / 5735
i/len(df): 363 / 5735
i/len(df): 364 / 5735
{'bytes': np.int64(89648), 'total_word_count': np.int64(8619)}
i/len(df): 365 / 5735
i/len(df): 366 / 5735
i/len(df): 367 / 5735
i/len(df): 368 / 5735
i/len(df): 369 / 5735
i/len(df): 370 / 5735
i/len(df): 371 / 5735
{'bytes': np.int64(28468), 'total_word_count': np.int64(1173)}
i/len(df): 372 / 5735
i/len(df): 373 / 5735
{'bytes': np.int64(92819), 'total_word_count': np.int64(552)}
i/len(df): 374 / 5735
i/len(df): 375 / 5735
{'bytes': np.int64(223300), 'total_word_count': np.int64(7206)}
i/len(df): 376 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 377 / 5735
{'bytes': np.int64(210563), 'total_word_count': np.int64(14703)}
i/len(df): 378 / 5735
i/len(df): 379 / 5735
i/len(df): 380 / 5735
i/len(df): 381 / 5735
i/len(df): 382 / 5735
i/len(df): 383 / 5735
i/len(df): 384 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 385 / 5735
{'bytes': np.int64(334550), 'total_word_count': np.int64(15163)}
i/len(df): 386 / 5735
i/len(df): 387 / 5735
i/len(df): 388 / 5735
i/len(df): 389 / 5735
i/len(df): 390 / 5735
i/len(df): 391 / 5735
i/len(df): 392 / 5735
i/len(df): 393 / 5735
i/len(df): 394 / 5735
{'bytes': np.int64(215981), 'total_word_count': np.int64(8200)}
i/len(df): 395 / 5735
i/len(df): 396 / 5735
i/len(df): 397 / 5735
i/len(df): 398 / 5735
i/len(df): 399 / 5735
i/len(df): 400 / 5735
i/len(df): 401 / 5735
i/len(df): 402 / 5735
i/len(df): 403 / 5735
{'bytes': np.int64(399055), 'total_word_count': np.int64(34124)}
i/len(df): 404 / 5735
i/len(df): 405 / 5735
i/len(df): 406 / 5735
i/len(df): 407 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 408 / 5735
{'bytes': np.int64(82227), 'total_word_count': np.int64(2299)}
i/len(df): 409 / 5735
i/len(df): 410 / 5735
i/len(df): 411 / 5735
i/len(df): 412 / 5735
i/len(df): 413 / 5735
i/len(df): 414 / 5735
i/len(df): 415 / 5735
{'bytes': np.int64(90984), 'total_word_count': np.int64(0)}
i/len(df): 416 / 5735
{'bytes': np.int64(24683), 'total_word_count': np.int64(475)}
i/len(df): 417 / 5735
i/len(df): 418 / 5735
{'bytes': np.int64(22409), 'total_word_count': np.int64(264)}
i/len(df): 419 / 5735
i/len(df): 420 / 5735
i/len(df): 421 / 5735
i/len(df): 422 / 5735
i/len(df): 423 / 5735
i/len(df): 424 / 5735
i/len(df): 425 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 426 / 5735
i/len(df): 427 / 5735
i/len(df): 428 / 5735
i/len(df): 429 / 5735
i/len(df): 430 / 5735
i/len(df): 431 / 5735
i/len(df): 432 / 5735
i/len(df): 433 / 5735
i/len(df): 434 / 5735
i/len(df): 435 / 5735
i/len(df): 436 / 5735
i/len(df): 437 / 5735
i/len(df): 438 / 5735
i/len(df): 439 / 5735
i/len(df): 440 / 5735
i/len(df): 441 / 5735
i/len(df): 442 / 5735
i/len(df): 443 / 5735
i/len(df): 444 / 5735
{'bytes': np.int64(122055), 'total_word_count': np.int64(4779)}
i/len(df): 445 / 5735
i/len(df): 446 / 5735
i/len(df): 447 / 5735
i/len(df): 448 / 5735
i/len(df): 449 / 5735
i/len(df): 450 / 5735
{'bytes': np.int64(23560), 'total_word_count': np.int64(265)}
i/len(df): 451 / 5735
i/len(df): 452 / 5735
i/len(df): 453 / 5735
i/len(df): 454 / 5735
i/len(df): 455 / 5735
i/len(df): 456 / 5735
i/len(df): 457 / 5735
{'bytes': np.int64(25983), 'total_word_count': np.int64(651)}
i/len(df): 458 / 5735
i/len(df): 459 / 5735
i/len(df): 460 / 5735
i/len(df): 461 / 5735
i/len(df): 462 / 5735
{'bytes': np.int64(146308), 'total_word_count': np.int64(6389)}
i/len(df): 463 / 5735
i/len(df): 464 / 5735
i/len(df): 465 / 5735
i/len(df): 466 / 5735
i/len(df): 467 / 5735
i/len(df): 468 / 5735
i/len(df): 469 / 5735
{'bytes': np.int64(24651), 'total_word_count': np.int64(284)}
i/len(df): 470 / 5735
i/len(df): 471 / 5735
i/len(df): 472 / 5735
i/len(df): 473 / 5735
i/len(df): 474 / 5735
{'bytes': np.int64(30358), 'total_word_count': np.int64(696)}
i/len(df): 475 / 5735
i/len(df): 476 / 5735
i/len(df): 477 / 5735
i/len(df): 478 / 5735
i/len(df): 479 / 5735
i/len(df): 480 / 5735
i/len(df): 481 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 482 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 483 / 5735
{'bytes': np.int64(1052917), 'total_word_count': np.int64(39843)}
i/len(df): 484 / 5735
i/len(df): 485 / 5735
i/len(df): 486 / 5735
i/len(df): 487 / 5735
i/len(df): 488 / 5735
i/len(df): 489 / 5735
i/len(df): 490 / 5735
i/len(df): 491 / 5735
i/len(df): 492 / 5735
{'bytes': np.int64(25503), 'total_word_count': np.int64(437)}
i/len(df): 493 / 5735
i/len(df): 494 / 5735
i/len(df): 495 / 5735
i/len(df): 496 / 5735
i/len(df): 497 / 5735
i/len(df): 498 / 5735
{'bytes': np.int64(103492), 'total_word_count': np.int64(379)}
i/len(df): 499 / 5735
i/len(df): 500 / 5735
i/len(df): 501 / 5735
i/len(df): 502 / 5735
i/len(df): 503 / 5735
i/len(df): 504 / 5735
i/len(df): 505 / 5735
{'bytes': np.int64(120477), 'total_word_count': np.int64(1034)}
i/len(df): 506 / 5735
i/len(df): 507 / 5735
i/len(df): 508 / 5735
i/len(df): 509 / 5735
i/len(df): 510 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 511 / 5735
{'bytes': np.int64(224020), 'total_word_count': np.int64(8010)}
i/len(df): 512 / 5735
i/len(df): 513 / 5735
i/len(df): 514 / 5735
i/len(df): 515 / 5735
i/len(df): 516 / 5735
i/len(df): 517 / 5735
{'bytes': np.int64(252016), 'total_word_count': np.int64(3134)}
i/len(df): 518 / 5735
i/len(df): 519 / 5735
i/len(df): 520 / 5735
i/len(df): 521 / 5735
i/len(df): 522 / 5735
i/len(df): 523 / 5735
i/len(df): 524 / 5735
{'bytes': np.int64(22849), 'total_word_count': np.int64(259)}
i/len(df): 525 / 5735
i/len(df): 526 / 5735
i/len(df): 527 / 5735
i/len(df): 528 / 5735
i/len(df): 529 / 5735
i/len(df): 530 / 5735
{'bytes': np.int64(86653), 'total_word_count': np.int64(494)}
i/len(df): 531 / 5735
i/len(df): 532 / 5735
i/len(df): 533 / 5735
i/len(df): 534 / 5735
i/len(df): 535 / 5735
i/len(df): 536 / 5735
{'bytes': np.int64(109289), 'total_word_count': np.int64(374)}
i/len(df): 537 / 5735
i/len(df): 538 / 5735
i/len(df): 539 / 5735
i/len(df): 540 / 5735
i/len(df): 541 / 5735
i/len(df): 542 / 5735
{'bytes': np.int64(28051), 'total_word_count': np.int64(614)}
i/len(df): 543 / 5735
i/len(df): 544 / 5735
i/len(df): 545 / 5735
i/len(df): 546 / 5735
i/len(df): 547 / 5735
i/len(df): 548 / 5735
i/len(df): 549 / 5735
i/len(df): 550 / 5735
{'bytes': np.int64(9679424), 'total_word_count': np.int64(50)}
i/len(df): 551 / 5735
i/len(df): 552 / 5735
i/len(df): 553 / 5735
i/len(df): 554 / 5735
i/len(df): 555 / 5735
i/len(df): 556 / 5735
i/len(df): 557 / 5735
i/len(df): 558 / 5735
i/len(df): 559 / 5735
i/len(df): 560 / 5735
{'bytes': np.int64(103970), 'total_word_count': np.int64(468)}
i/len(df): 561 / 5735
i/len(df): 562 / 5735
i/len(df): 563 / 5735
i/len(df): 564 / 5735
i/len(df): 565 / 5735
i/len(df): 566 / 5735
{'bytes': np.int64(307278), 'total_word_count': np.int64(5145)}
i/len(df): 567 / 5735
i/len(df): 568 / 5735
i/len(df): 569 / 5735
i/len(df): 570 / 5735
i/len(df): 571 / 5735
i/len(df): 572 / 5735
i/len(df): 573 / 5735
i/len(df): 574 / 5735
i/len(df): 575 / 5735
{'bytes': np.int64(42468), 'total_word_count': np.int64(1566)}
i/len(df): 576 / 5735
i/len(df): 577 / 5735
i/len(df): 578 / 5735
i/len(df): 579 / 5735
{'bytes': np.int64(55849), 'total_word_count': np.int64(2755)}
i/len(df): 580 / 5735
i/len(df): 581 / 5735
i/len(df): 582 / 5735
i/len(df): 583 / 5735
i/len(df): 584 / 5735
i/len(df): 585 / 5735
i/len(df): 586 / 5735
i/len(df): 587 / 5735
{'bytes': 0, 'total_word_count': 0}
i/len(df): 588 / 5735
{'bytes': np.int64(233356), 'total_word_count': np.int64(16691)}
i/len(df): 589 / 5735
i/len(df): 590 / 5735
i/len(df): 591 / 5735
i/len(df): 592 / 5735
i/len(df): 593 / 5735
i/len(df): 594 / 5735
i/len(df): 595 / 5735
i/len(df): 596 / 5735
i/len(df): 597 / 5735
i/len(df): 598 / 5735
{'bytes': np.int64(25648), 'total_word_count': np.int64(324)}
i/len(df): 599 / 5735
i/len(df): 600 / 5735
i/len(df): 601 / 5735
i/len(df): 602 / 5735
i/len(df): 603 / 5735
i/len(df): 604 / 5735
{'bytes': np.int64(28121), 'total_word_count': np.int64(564)}
i/len(df): 605 / 5735
i/len(df): 606 / 5735
i/len(df): 607 / 5735
i/len(df): 608 / 5735
i/len(df): 609 / 5735
{'bytes': np.int64(25688), 'total_word_count': np.int64(524)}
i/len(df): 610 / 5735
i/len(df): 611 / 5735
i/len(df): 612 / 5735
i/len(df): 613 / 5735
i/len(df): 614 / 5735
i/len(df): 615 / 5735
{'bytes': np.int64(93777), 'total_word_count': np.int64(5719)}
i/len(df): 616 / 5735
i/len(df): 617 / 5735
i/len(df): 618 / 5735
i/len(df): 619 / 5735
i/len(df): 620 / 5735
i/len(df): 621 / 5735
i/len(df): 622 / 5735
i/len(df): 623 / 5735
{'bytes': np.int64(40303), 'total_word_count': np.int64(653)}
i/len(df): 624 / 5735
i/len(df): 625 / 5735
i/len(df): 626 / 5735
i/len(df): 627 / 5735
i/len(df): 628 / 5735
i/len(df): 629 / 5735

In [49]:

add_case_attribute(df, get_month_attribute(), 'case:start_month')
add_case_attribute(df, get_weekday_attribute(), "case:start_weekday")
add_case_attribute(df, get_urheber_first_activity(), "case:author_first_activity")
add_case_attribute(df, get_urheber_count_first_activity(), "case:author_first_activity_count")
add_case_attribute(df, get_WIP_during_start(), "case:WIP_during_start")
#add_pdf_case_attributes(df, pdf_info_bytes, pdf_info_word_count, "case:pdf_bytes", "case:pdf_word_count")
add_pdf_case_attributes_otherDoc(df, pdf_info_bytes, pdf_info_word_count, "case:pdf_bytes", "case:pdf_word_count")
data, data_af = get_professionalism_data()

add_case_attribute(df, get_professionalism_values(data[bundeslandCapitalized.lower()], "squire"), "case:squire")
add_case_attribute(df, get_professionalism_values(data[bundeslandCapitalized.lower()], "salary"), "case:salary")
add_case_attribute(df, get_professionalism_values(data[bundeslandCapitalized.lower()], "staff"), "case:staff")
add_case_attribute(df, get_professionalism_values(data[bundeslandCapitalized.lower()], "commDays"), "case:commDays")
add_case_attribute(df, get_professionalism_values(data[bundeslandCapitalized.lower()], "plenDays"), "case:plenDays")
add_case_attribute(df, get_professionalism_values(data_af[bundeslandCapitalized.lower()], "afScore"), "case:af_score")
add_case_attribute(df, get_is_passed_bill(), "case:is_passed_bill")

Mapping bytes:
  case:concept:name  case:pdf_bytes
0             84208          197170
1             84275           54723
2             84277          577141
3             84276          125855
4             84208          197170
Mapping word count:
  case:concept:name  case:pdf_word_count
0             84208                 3692
1             84275                 2607
2             84277                10758
3             84276                 6503
4             84208                 3692

/var/folders/c0/znjbgdp95852r1d2gl38_cl40000gn/T/ipykernel_16441/3754736861.py:165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[bundesland.lower()]['squire'] = 1/3 * (data[bundesland.lower()]['salary'] / data[bundesland.lower()]['fp_mp_salary_2015']) + \

In [50]:
df[df["case:is_passed_bill"] == 1]["case:concept:name"].nunique()

550

In [51]:
add_case_attribute(df, get_is_election_year(), "case:is_election_year")

# enrich with data from csv files created through performance analysis

frequencies = pd.read_csv('../Frequency_yearly_Gesetzgebung.csv')
cycle_times = pd.read_csv('../Cycle Time_yearly_Gesetzgebung.csv')
arrival_rates = pd.read_csv('../Inter-arrival Time_yearly_Gesetzgebung.csv')
variants = pd.read_csv('../Variants_yearly_Gesetzgebung.csv')

def get_yearly_data_from_csv(data):
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        year = df[TIMESTAMP_COL][i].year
        if case_id not in result_obj:
            if (data.loc[data['year'] == year, bundeslandCapitalized].empty):
                result_obj[case_id] = None
            else:
                result_obj[case_id] = data.loc[data['year'] == year, bundeslandCapitalized].values[0]
    return result_obj

add_case_attribute(df, get_yearly_data_from_csv(frequencies), "case:yearly_frequency")
add_case_attribute(df, get_yearly_data_from_csv(cycle_times), "case:yearly_cycle_time")
add_case_attribute(df, get_yearly_data_from_csv(arrival_rates), "case:yearly_arrival_rate")
add_case_attribute(df, get_yearly_data_from_csv(variants), "case:yearly_variants")

df.head()

,lifecycle:transition,time:timestamp,DBID,ReihNr,DokArt,DokArtL,DokTyp,DokTypL,Desk,Titel,...,case:staff,case:commDays,case:plenDays,case:af_score,case:is_passed_bill,case:is_election_year,case:yearly_frequency,case:yearly_cycle_time,case:yearly_arrival_rate,case:yearly_variants
0,complete,2006-01-03 01:00:00+00:00,D-169281,1,Drs,Drucksache,Antr (GesEntw),Antrag (Gesetzentwurf),Tierschutz,Gesetz zur Einführung der tierschutzrechtliche...,...,80610.859375,106.0,24,-0.27513,0,1,32,89.97,10.55,27
1,complete,2006-01-10 01:00:00+00:00,D-169581,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Meldewesen,Erstes Gesetz zur Änderung des Landespersonala...,...,80610.859375,106.0,24,-0.27513,1,1,32,89.97,10.55,27
2,complete,2006-01-10 01:00:00+00:00,D-169587,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Polizeiausbildung,Gesetz zu dem Abkommen zur Änderung des Abkomm...,...,80610.859375,106.0,24,-0.27513,1,1,32,89.97,10.55,27
3,complete,2006-01-10 01:00:00+00:00,D-169584,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Öffentliche Sicherheit und Ordnung,Fünftes Gesetz zur Änderung des Allgemeinen Si...,...,80610.859375,106.0,24,-0.27513,1,1,32,89.97,10.55,27
4,complete,2006-01-12 01:00:00+00:00,D-169282,2,PlPr,Plenarprotokoll,I. Lesung,I. Lesung,nan,nan,...,80610.859375,106.0,24,-0.27513,0,1,32,89.97,10.55,27

In [52]:
# one-hot encoding for urheber

all_urheber = df["Urheber"].unique()

def determine_origin_feature_name(urheber, urheber_feature_names):
    if "ausschuss" in urheber.lower():
        if "ausschuss" not in urheber_feature_names:
            urheber_feature_names.append("ausschuss")
    elif urheber.lower() not in urheber_feature_names:
        urheber_feature_names.append(urheber.lower())

urheber_feature_names = []
for urheber in all_urheber:
    if isinstance(urheber, str):
        if (urheber.startswith("[") and urheber.endswith("]")):
            urheber_list = ast.literal_eval(urheber)
            for urheber in urheber_list:
                determine_origin_feature_name(urheber, urheber_feature_names)
        else:
            determine_origin_feature_name(urheber, urheber_feature_names)


def get_urheber_first_activity(urheber_feature_name):
    result_obj = {}
    for i in range(len(df)):
        case_id = df[CASE_ID_COL][i]
        if case_id not in result_obj:
            urheber = df["Urheber"][i]
            if (urheber.startswith("[") and urheber.endswith("]")):
                urheber_list = ast.literal_eval(urheber)
                urheber_list = [u.lower() for u in urheber_list]
                if urheber_feature_name in urheber_list:
                    result_obj[case_id] = 1
                else:
                    result_obj[case_id] = 0       
            else:
                if urheber.lower() == urheber_feature_name:
                    result_obj[case_id] = 1
                else:
                    result_obj[case_id] = 0         
    return result_obj

for urheber_feature_name in urheber_feature_names:
    add_case_attribute(df, get_urheber_first_activity(urheber_feature_name), "case:author_first_activity_" + urheber_feature_name)

In [53]:
#activities = df[df[CASE_ID_COL] == df.iloc[3749]["case:concept:name"]]
#print(activities["time:timestamp"])

df.head()

,lifecycle:transition,time:timestamp,DBID,ReihNr,DokArt,DokArtL,DokTyp,DokTypL,Desk,Titel,...,case:author_first_activity_bündnis 90/die grünen (grüne),case:author_first_activity_nan,case:author_first_activity_ausschuss,case:author_first_activity_sozialdemokratische partei deutschlands (spd),case:author_first_activity_partei des demokratischen sozialismus (die linkspartei.pds),case:author_first_activity_freie demokratische partei (fdp),case:author_first_activity_christlich demokratische union deutschlands (cdu),case:author_first_activity_die linke fraktion berlin (die linke),case:author_first_activity_piraten (piraten),case:author_first_activity_alternative für deutschland (afd)
0,complete,2006-01-03 01:00:00+00:00,D-169281,1,Drs,Drucksache,Antr (GesEntw),Antrag (Gesetzentwurf),Tierschutz,Gesetz zur Einführung der tierschutzrechtliche...,...,1,0,0,0,0,0,0,0,0,0
1,complete,2006-01-10 01:00:00+00:00,D-169581,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Meldewesen,Erstes Gesetz zur Änderung des Landespersonala...,...,0,1,0,0,0,0,0,0,0,0
2,complete,2006-01-10 01:00:00+00:00,D-169587,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Polizeiausbildung,Gesetz zu dem Abkommen zur Änderung des Abkomm...,...,0,1,0,0,0,0,0,0,0,0
3,complete,2006-01-10 01:00:00+00:00,D-169584,1,Drs,Drucksache,VorlBeschl (GesEntw),Vorlage zur Beschlussfassung (Gesetzentwurf),Öffentliche Sicherheit und Ordnung,Fünftes Gesetz zur Änderung des Allgemeinen Si...,...,0,1,0,0,0,0,0,0,0,0
4,complete,2006-01-12 01:00:00+00:00,D-169282,2,PlPr,Plenarprotokoll,I. Lesung,I. Lesung,nan,nan,...,1,0,0,0,0,0,0,0,0,0

In [54]:
pm4py.write_xes(df[df["case:is_passed_bill"] == 1], OUTPUT_FILE_NAME)
#pm4py.write_xes(df[df["case:is_passed_bill"] == 1], OUTPUT_FILE_NAME.replace(".xes", "_passed_bills.xes"))

'''
df_passed_bills = df[df["case:is_passed_bill"] == 1]

# since proM performance spectrum miner does not like it "," needs to be removed 
df_passed_bills["concept:name"] = df_passed_bills["concept:name"].str.replace(',', '')
df_passed_bills["concept:name"] = df_passed_bills["concept:name"].str.lstrip()

pm4py.write_xes(df_passed_bills, OUTPUT_FILE_NAME.replace(".xes", "_passed_bills_performanceSpectrum.xes"))
'''

exporting log, completed traces :: 100%|██████████| 550/550 [00:00<00:00, 2916.12it/s]

'\ndf_passed_bills = df[df["case:is_passed_bill"] == 1]\n\n# since proM performance spectrum miner does not like it "," needs to be removed \ndf_passed_bills["concept:name"] = df_passed_bills["concept:name"].str.replace(\',\', \'\')\ndf_passed_bills["concept:name"] = df_passed_bills["concept:name"].str.lstrip()\n\npm4py.write_xes(df_passed_bills, OUTPUT_FILE_NAME.replace(".xes", "_passed_bills_performanceSpectrum.xes"))\n'